# Generated by Django 5.2.4 on 2025-08-07 11:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='business_image')),
            ],
        ),
    ]
